export { default as CommonLoading } from './CommonLoading';
export { default as WaveLoading } from './WaveLoading';
export { default as CircleLoading } from './CircleLoading';
export { default as LoopCircleLoading } from './LoopCircleLoading';
export { default as TransverseLoading } from './TransverseLoading';
export { default as BlockLoading } from './BlockLoading';
export { default as BoxLoading  } from './BoxLoading'
export { default as CircleToBlockLoading } from './CircleToBlockLoading'
export { default as TouchBallLoading } from './TouchBallLoading'
export { default as DisappearedLoading } from './DisappearedLoading'
export { default as BlockReserveLoading } from './BlockReserveLoading'
export { default as WaveTopBottomLoading } from './WaveTopBottomLoading'
export { default as NineCellLoading } from './NineCellLoading'
export { default as WindMillLoading } from './WindMillLoading'
export { default as BabelLoading } from './BabelLoading'
export { default as JumpCircleLoading } from './JumpCircleLoading'
export { default as MeteorRainLoading } from './MeteorRainLoading'
export { default as RotateCircleLoading } from './RotateCircleLoading'
export { default as StickyBallLoading } from './StickyBallLoading'
export { default as SemipolarLoading } from './SemipolarLoading'
